[package]
name = "fallingsand_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-hash = "1.1"
itertools = "0.10"
parry2d = "0.10"
rayon = "1.5"
bincode = "1.3"

[[bench]]
name = "simulation"
