[package]
name = "fallingsand"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[workspace]
members = [
    "fallingsand_sim",
    "fallingsand_net",
    "fallingsand_orchestrator",
]

[dependencies]
fallingsand_sim = { path = "fallingsand_sim" }
fallingsand_net = { path = "fallingsand_net" }
bevy = { version = "0.8", features = ["dynamic"] }
bevy_pixel_buffer = "0.2"

[profile.dev.package.fallingsand_sim]
opt-level = 1
