[target.x86_64-pc-windows-msvc]
linker = "rust-lld.exe"
rustdocflags = ["-Clinker=rust-lld.exe"]

[target.wasm32-unknown-unknown]
rustflags = [
    '--cfg',
    'getrandom_backend="wasm_js"',
    '--cfg=web_sys_unstable_apis',
]

[env]
BEVY_ASSET_ROOT = { value = "", relative = true }

[alias]
dev = "run -p fallingsand_client --features dev"
dev-server = "run -p fallingsand_server"
profile = "run -p fallingsand_client --profile perf --features profiling"
profile-server = "run -p fallingsand_server --profile perf --features tracy"
